### ISSUE TITLE
请求挂到 LeanCloud Demos 展示页

### ISSUE THREAD

**Issue by lzwjava** [daimajia/AnimeTaste#21]
Hi, @daimajia  , 刚看到这款很棒的应用，用了 LeanCloud，能否挂到 [LeanCloud-Demos](https://github.com/leancloud/leancloud-demos) 页面？好让其它开发者参考学习。

也请问能否在 AnimeTaste 项目主页了，稍微提一下 LeanCloud ？

Thanks！
lzwjava
LeanCloud

**Comment by Tedko** [comment]
this kind of stuff should not be an issue.
though I do appreciate your works.

**Comment by lzwjava** [comment]
Fine, close it now.
