### ISSUE TITLE
编译不过去

### ISSUE THREAD

**Issue by JunWeiUp** [daimajia/AnimeTaste#24]
Error:(34, 13) Failed to resolve: com.afollestad:material-dialogs:0.7.3.1
<a href="openFile:D:/unlook/AnimeTaste-master/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by wanyt** [comment]
在build.gradle里面把com.afollestad:material-dialogs:0.7.3.1改成com.afollestad.material-dialogs:core:0.9.0.0就好了

**Comment by daimajia** [comment]
Thanks @wanyt , the latest commit fixed this issue.
https://github.com/daimajia/AnimeTaste/commit/a63d3df7c4bbe8ae6d82c576e5303eb9940bc35a
